# Generated by Django 5.1.3 on 2024-11-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
