# Generated by Django 5.1.3 on 2024-12-07 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('amount', models.PositiveBigIntegerField()),
                ('interest_rate', models.PositiveSmallIntegerField()),
                ('payments_amount', models.PositiveSmallIntegerField()),
                ('montly_return', models.PositiveIntegerField()),
                ('term', models.PositiveSmallIntegerField()),
                ('term_type', models.CharField(choices=[('M', 'months'), ('Y', 'years')], max_length=1)),
                ('anual_rate', models.PositiveSmallIntegerField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.investor')),
            ],
        ),
    ]
